### ISSUE TITLE
添加依赖，没有成功

### ISSUE THREAD

**Issue by lvtanxi** [xionghuiCoder/spring-boot-starter-dubbo#2]
`<dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>spring-boot-starter-dubbo</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </dependency>
`
应该是这样的，但是没有引用成功

**Comment by yindz** [comment]
中央仓库还没有这个。我是本地install解决的。

**Comment by xionghuiCoder** [comment]
目前木有发布release版本; 也没有发布到中央仓库; 需要clone下来是使用snapshot版本
