### ISSUE TITLE
为什么不也把@Service替换？

### ISSUE THREAD

**Issue by jonathanzhan** [xionghuiCoder/spring-boot-starter-dubbo#5]
我看了下源码，已经把@Reference替换成@DubboConsumer，为什么不把@Service也替换掉呢？有什么特殊的考虑吗

**Comment by xionghuiCoder** [comment]
当时考虑的是@Reference和@DubboConsumer的配置并不是完全一样的(@DubboConsumer支持的配置有限), 而provider的@Service的配置是完全一样的
