### ISSUE TITLE
配置多个zookeeper://xxxx:xx 报错

### ISSUE THREAD

**Issue by kkzy** [xionghuiCoder/spring-boot-starter-dubbo#6]
zookeeper://60.111.63.189:2181,60.111.65.74:2181,60.111.64.215:2181

yml里这么写报错，求帮忙

**Comment by xionghuiCoder** [comment]
dubbo解析多个注册地址的正则表达式是:Pattern.compile("\\s*[|;]+\\s*") ；可以尝试下面的配置: zookeeper://60.111.63.189:2181;zookeeper://60.111.65.74:2181;zookeeper://60.111.64.215:2181
